### PR TITLE
Dev v0.4

### LINKED ISSUE #3: Ultrasonic sensors mounting position
It would be better to mount the ultra sonic sensors from the inner side of the robot, so there would be only two big holes for the transmitter and receiver. Maybe it is enough to clamp them by making the holes tight enough. 
This way the sensors could be protected better from the enviroment ( rain, crashes, ... ).

### PR DESCRIPTION
**Pull request by generationmake**
release v0.4.

### CODE REVIEW

**Comment by generationmake** [comment]
Hi @wuehr1999 
I am about to clean up this PR.
Any idea what the model "case" is for?
Thanks

**Comment by wuehr1999** [comment]
Hi @generationmake,
it is the case for this [controller project](https://github.com/wuehr1999/JECCbotECU). As it is also documented here, we could think about removing it from the JECCbot_mini main repository.

**Comment by generationmake** [comment]
> Hi @generationmake, it is the case for this [controller project](https://github.com/wuehr1999/JECCbotECU). As it is also documented here, we could think about removing it from the JECCbot_mini main repository.

If it is also in the other repository we wont need it here and only import the step files if necessary.
I will delete the file.

**Comment by generationmake** [comment]
Good morning @wuehr1999 
could you have a short look at the data and check if you spot any issues?
If not I will merge.
Thanks

**Comment by wuehr1999** [comment]
Hi @generationmake 
lgtm :-)

**Pull request merged**
